// Generated by ReScript, PLEASE EDIT WITH CARE


function getElementById(id) {
  return document.getElementById(id);
}

function addClass(element, className) {
  return element.classList.add(className);
}

function removeClass(element, className_1, className_2) {
  return element.classList.remove(className_1, className_2);
}

var textEditor = document.getElementById("textEditor");

var textView = document.getElementById("textView");

function updateTextView($$event) {
  textView.innerText = $$event.target.value;
  
}

textEditor.addEventListener("input", updateTextView);

function selectSize(size) {
  switch (size) {
    case /* Small */0 :
        addClass(textView, "text-sm");
        return removeClass(textView, "text-2xl", "text-6xl");
    case /* Regular */1 :
        addClass(textView, "text-2xl");
        return removeClass(textView, "text-sm", "text-6xl");
    case /* Large */2 :
        addClass(textView, "text-6xl");
        return removeClass(textView, "text-sm", "text-2xl");
    
  }
}

var selectSmall = document.getElementById("selectSmall");

var selectRegular = document.getElementById("selectRegular");

var selectLarge = document.getElementById("selectLarge");

selectSmall.addEventListener("change", (function (param) {
        return selectSize(/* Small */0);
      }));

selectRegular.addEventListener("change", (function (param) {
        return selectSize(/* Regular */1);
      }));

selectLarge.addEventListener("change", (function (param) {
        return selectSize(/* Large */2);
      }));

selectSize(/* Regular */1);

export {
  getElementById ,
  addClass ,
  removeClass ,
  textEditor ,
  textView ,
  updateTextView ,
  selectSize ,
  selectSmall ,
  selectRegular ,
  selectLarge ,
  
}
/* textEditor Not a pure module */
